apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: hbrfmsju0-go-gitops
  description: This is GitOps manifest for hbrfmsju0-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=hbrfmsju0-go
    backstage.io/kubernetes-id: hbrfmsju0-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: hbrfmsju0-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:hbrfmsju0-go
